"""Database creation imperative method

Revision ID: 0d0be0860ef3
Revises: 
Create Date: 2024-08-07 14:10:33.533436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0be0860ef3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('login', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('folders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text_folder', sa.String(), nullable=False),
                    sa.Column('number_of_topics', sa.Integer(), nullable=True),
                    sa.Column('last_open_date_time', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id']),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('knowledge_queues',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content_knowledge_queue', sa.String(), nullable=False),
                    sa.Column('completed_task_status', sa.Boolean(), nullable=True),
                    sa.Column('number_of_cycles', sa.Integer(), nullable=True),
                    sa.Column('create_date_time', sa.DateTime(), nullable=True),
                    sa.Column('next_alert_card', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id']),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('themes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name_theme', sa.String(), nullable=False),
                    sa.Column('last_open_date_time', sa.DateTime(), nullable=True),
                    sa.Column('number_of_records', sa.Integer(), nullable=True),
                    sa.Column('folder_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['folder_id'], ['folders.id']),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('records',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name_record', sa.String(), nullable=False),
                    sa.Column('text_records', sa.String(), nullable=True),
                    sa.Column('last_open_date_time', sa.DateTime(), nullable=True),
                    sa.Column('count_text', sa.Integer(), nullable=True),
                    sa.Column('theme_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['theme_id'], ['themes.id']),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('themes')
    op.drop_table('knowledge_queues')
    op.drop_table('folders')
    op.drop_table('users')
    # ### end Alembic commands ###
