"""tests_for_db_test

Revision ID: c5fcb36a4d25
Revises: 8b6a75f1a84e
Create Date: 2024-08-13 18:08:30.004418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fcb36a4d25'
down_revision: Union[str, None] = '8b6a75f1a84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
